name: GitHub Actions for Frontend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3  

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up Docker cache 
      - name: Cache Docker layers
        uses: actions/cache@v3  
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Install dependencies and run tests (security analysis)
      - name: Install Dependencies and run tests
        run: |
          npm install
          npm audit --production --json | tee audit-results.json

      # Security check: Run Trivy scan on base image (Docker vulnerability scan)
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
            image: ${{ github.repository }}:${{ github.sha }} 


      # Build Docker image with timestamp as tag
      - name: Build Docker image
        run: |
          IMAGE_TAG=$(date +'%Y%m%d%H%M%S')  # Generate timestamp as tag
          docker build -t ${{ github.repository }}:$IMAGE_TAG .
          
      # Push Docker image to Docker Hub or GitHub Container Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker image to Registry
        run: |
          docker push ${{ github.repository }}:${{ github.sha }}

      # Snyk Security scan (Scan for known vulnerabilities in dependencies)
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          image: ${{ github.repository }}:${{ github.sha }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Notify via Slack on Success
      - name: Notify via Slack on Success
        if: success()
        uses: Ilshidur/action-slack@2.1.0  
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: "#alert-and-notification"  
          message: "Deployment successful for commit ${{ github.sha }}"

      # Notify via Slack on Failure
      - name: Notify via Slack on Failure
        if: failure()
        uses: Ilshidur/action-slack@2.1.0  
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: "#alert-and-notification"  
          message: "Deployment failed for commit ${{ github.sha }}"
